'depth': 10
'min_density': 0.1
'n_threads': -1
'downsample': False
'voxel_size': 0.05
'max_nn': 20
'pc_range':  [-8, -8, -8, 8, 8, 8]
'occ_size':  [400, 400, 400]
'self_range': [3.0, 1.5, 2.0]
'ray_cast_step_size': 1.0
'interval': 10
'voxel_size_scale': 100.0
